name: Dagger CI/CD

on: [push]

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run tests
        uses: dagger/dagger-for-github@8.0.0
        with:
          module: dagger
          call: run-tests --dir .
          version: "latest"
