name: Dagger CI/CD

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run tests
        uses: dagger/dagger-for-github@8.0.0
        with:
          module: .dagger
          call: run-tests --dir .
          version: "latest"

  on-success:
    needs: tests
    if : success()
    runs-on: ubuntu-latest
    steps:
      - name: deployed successfully
        run: echo code deployed successfully
        # run: echo ${{secrets.GH_TOKEN}}

  on-failure:
    needs: tests
    if : failure()
    runs-on: ubuntu-latest
    steps:
      - name: deployment failed
        run: echo code failed to deploy
