- name: Hello
  uses: dagger/dagger-for-github@8.0.0
  with:
    module: github.com/shykes/daggerverse/hello
    call: hello --greeting Hola --name Jeremy
    cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
    version: "latest"  # semver x.y.z
